spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: Hero
          uri: lb://Hero
          predicates:
            - Path=/api/hero/**
        - id: Categories
          uri: lb://Categories
          predicates:
            - Path=/categories,/categories/**
        - id: CategoriesBrands
          uri: lb://Categories
          predicates:
            - Path=/api/brands,/api/brands/**
        - id: CategoriesSizes
          uri: lb://Categories
          predicates:
            - Path=/api/sizes,/api/sizes/**
        - id: Category
          uri: lb://Category
          predicates:
            - Path=/api/category/**
        - id: NewArrivalss
          uri: lb://NewArrivalss
          predicates:
            - Path=/api/products/**
        - id: Explores
          uri: lb://Explores
          predicates:
            - Path=/api/Explores/**
        - id: ExploreAll
          uri: lb://ExploreAll
          predicates:
            - Path=/api/allproducts/**
        - id: TrackOrder
          uri: lb://TrackOrder
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: Checkout
          uri: lb://Checkout
          predicates:
            - Path=/api/checkout/**
        - id: login
          uri: lb://logins
          predicates:
            - Path=/api/auth/**
        - id: CartAPICart
          uri: lb://CartAPISS
          predicates:
            - Path=/api/cart/**
        - id: CartAPIWishlist
          uri: lb://CartAPISS
          predicates:
            - Path=/api/wishlist/**
        - id: CartAPIBills
          uri: lb://CartAPISS
          predicates:
            - Path=/api/bills/**
        - id: CartAPIOffers
          uri: lb://CartAPISS
          predicates:
            - Path=/api/offers/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
server:
  port: 8305